### PR TITLE
Fix duplicate azure key

### PR DESCRIPTION
**Pull request by BastianZim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fix duplicate azure key which hold sup python 3.11 migration: https://conda-forge.org/status/

### CODE REVIEW

**Comment by BastianZim** [comment]
@conda-forge-admin, please rerender

**Comment by petrushy** [comment]
Many thanks for the fix!

**Comment by petrushy** [comment]
btw, do you know if it is possible to trigger also a python 3.11 version update of the project somehow?

**Comment by BastianZim** [comment]
That will be done by a bot over the next few days, since this is now resolved. 
It might take some time though as the bot only sporadically checks and there is no way to do it manually.

**Pull request merged**
