### PR TITLE
Development version of JCC

### PR DESCRIPTION
**Pull request by petrushy**

### CODE REVIEW

**Comment by jakirkham** [comment]
We haven't officially setup a way to dev releases. Unofficially we put them in a different label. The last ref is both cautionary and instructive.

ref: https://github.com/conda-forge/conda-forge-enhancement-proposals/pull/3
ref: https://github.com/conda-forge/matplotlib-feedstock/pull/24#issuecomment-221496870

**Comment by jakirkham** [comment]
Should add the target branch of this PR would need to change.

The key is adding the following to `conda-forge.yml` and then re-rendering afterwards.

```yaml
channels:
  targets:
    - [conda-forge, rc]
```

**Comment by petrushy** [comment]
Hi, Thanks for the info, in general i don't like "dev" versions but the JCC project has some issues with the release process and I'm not sure if and when there will be "firm" versions again. This dev version fixes some neccessary bugs in the previous "firm" version.

**Comment by petrushy** [comment]
Or maybe it's a better approach to use the previous version number but increase the build number just?

**Comment by jakirkham** [comment]
There are certainly valid reasons to use dev releases. Sounds like you have found one of them.

We've discussed with `conda` developers about how we could make dev releases a bit nicer. For example currently using the `dev` label can open one up to getting all sorts of things as dev packages that you might not want dev packages of. This has been the main blocker to making progress on them in conda-forge.

Ideally one should be able to get select things as dev packages. FWICT this sort of problem should be more tractable with `conda` 4.4 as one can specify a package come from a certain channel (e.g. `conda-forge/label/dev`), but not fall into the traps that adding the `dev` channel globally would cause.

**Comment by petrushy** [comment]
Thanks, i'll keep it as a dev package!

One other question with this recepie is that I use a bit ugly nailing of the version of openjdk. The openjdk in the conda-forge is not complete and this recepie needs a full one like the one in the anaconda channel. https://github.com/conda-forge/openjdk-feedstock/issues/12

Do you know if there is a good way to restrict the dependency to the anaconda packages?

**Pull request merged**
